/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ActionConfigProperty } from './actionConfigProperty';

export class ActionConfig {
    'properties': ActionConfigProperty;
    'type': ActionConfig.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "properties",
            "baseName": "properties",
            "type": "ActionConfigProperty"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ActionConfig.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return ActionConfig.attributeTypeMap;
    }
}

export namespace ActionConfig {
    export enum TypeEnum {
        ChangeSpeedClassAction = <any> 'ChangeSpeedClassAction',
        InvokeAwsLambdaAction = <any> 'InvokeAWSLambdaAction',
        ExecuteWebRequestAction = <any> 'ExecuteWebRequestAction',
        SendMailAction = <any> 'SendMailAction',
        SendMailToOperatorAction = <any> 'SendMailToOperatorAction',
        ActivationAction = <any> 'ActivationAction',
        DeactivationAction = <any> 'DeactivationAction',
        StandbyAction = <any> 'StandbyAction',
        SuspendAction = <any> 'SuspendAction'
    }
}
