/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { APICallErrorMessage } from './aPICallErrorMessage';

export class APICallError {
    'errorMessage'?: APICallErrorMessage;
    'httpStatus'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "errorMessage",
            "baseName": "errorMessage",
            "type": "APICallErrorMessage"
        },
        {
            "name": "httpStatus",
            "baseName": "httpStatus",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return APICallError.attributeTypeMap;
    }
}

