/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ArcSessionStatus {
    /**
    * Arc サーバーから受信した WireGuard AllowedIPs が表示されます。
    */
    'arcAllowedIPs'?: Array<string>;
    /**
    * クライアントの IP アドレスです。
    */
    'arcClientPeerIpAddress'?: string;
    'arcClientPeerPublicKey'?: string;
    /**
    * Arc サーバーの WireGuard プロトコルのエンドポイントです。
    */
    'arcServerEndpoint'?: string;
    /**
    * Arc サーバーのサーバーピア公開鍵です。
    */
    'arcServerPeerPublicKey'?: string;
    'gatewayPrivateIpAddress'?: string;
    'gatewayPublicIpAddress'?: string;
    'lastUpdatedAt'?: number;
    'vpgId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "arcAllowedIPs",
            "baseName": "arcAllowedIPs",
            "type": "Array<string>"
        },
        {
            "name": "arcClientPeerIpAddress",
            "baseName": "arcClientPeerIpAddress",
            "type": "string"
        },
        {
            "name": "arcClientPeerPublicKey",
            "baseName": "arcClientPeerPublicKey",
            "type": "string"
        },
        {
            "name": "arcServerEndpoint",
            "baseName": "arcServerEndpoint",
            "type": "string"
        },
        {
            "name": "arcServerPeerPublicKey",
            "baseName": "arcServerPeerPublicKey",
            "type": "string"
        },
        {
            "name": "gatewayPrivateIpAddress",
            "baseName": "gatewayPrivateIpAddress",
            "type": "string"
        },
        {
            "name": "gatewayPublicIpAddress",
            "baseName": "gatewayPublicIpAddress",
            "type": "string"
        },
        {
            "name": "lastUpdatedAt",
            "baseName": "lastUpdatedAt",
            "type": "number"
        },
        {
            "name": "vpgId",
            "baseName": "vpgId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return ArcSessionStatus.attributeTypeMap;
    }
}

