/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class AuthRequest {
    'authKey'?: string;
    'authKeyId'?: string;
    'email'?: string;
    'mfaOTPCode'?: string;
    'operatorId'?: string;
    'password'?: string;
    'tokenTimeoutSeconds'?: number = 86400;
    'userName'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "authKey",
            "baseName": "authKey",
            "type": "string"
        },
        {
            "name": "authKeyId",
            "baseName": "authKeyId",
            "type": "string"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "mfaOTPCode",
            "baseName": "mfaOTPCode",
            "type": "string"
        },
        {
            "name": "operatorId",
            "baseName": "operatorId",
            "type": "string"
        },
        {
            "name": "password",
            "baseName": "password",
            "type": "string"
        },
        {
            "name": "tokenTimeoutSeconds",
            "baseName": "tokenTimeoutSeconds",
            "type": "number"
        },
        {
            "name": "userName",
            "baseName": "userName",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return AuthRequest.attributeTypeMap;
    }
}

