/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CouponResponse {
    /**
    * クーポン額
    */
    'amount'?: number;
    /**
    * 残高
    */
    'balance'?: number;
    /**
    * 対象課金アイテム
    */
    'billItemName'?: string;
    /**
    * クーポンコード
    */
    'couponCode'?: string;
    /**
    * 通貨
    */
    'currency'?: CouponResponse.CurrencyEnum;
    /**
    * 有効期限
    */
    'expiryYearMonth'?: string;
    /**
    * 発注 ID
    */
    'orderId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "balance",
            "baseName": "balance",
            "type": "number"
        },
        {
            "name": "billItemName",
            "baseName": "billItemName",
            "type": "string"
        },
        {
            "name": "couponCode",
            "baseName": "couponCode",
            "type": "string"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "CouponResponse.CurrencyEnum"
        },
        {
            "name": "expiryYearMonth",
            "baseName": "expiryYearMonth",
            "type": "string"
        },
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return CouponResponse.attributeTypeMap;
    }
}

export namespace CouponResponse {
    export enum CurrencyEnum {
        Jpy = <any> 'JPY',
        Usd = <any> 'USD',
        Eur = <any> 'EUR'
    }
}
