/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CreateEstimatedOrderRequestShippingOptionsInner } from './createEstimatedOrderRequestShippingOptionsInner';
import { OrderItemModel } from './orderItemModel';

export class CreateEstimatedOrderRequest {
    /**
    * 発注商品リスト
    */
    'orderItemList'?: Array<OrderItemModel>;
    /**
    * お受け取り希望日
    */
    'preferredDeliveryDate'?: string;
    /**
    * 商品発送先 ID
    */
    'shippingAddressId'?: string;
    /**
    * 配送オプション
    */
    'shippingOptions'?: Array<CreateEstimatedOrderRequestShippingOptionsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "orderItemList",
            "baseName": "orderItemList",
            "type": "Array<OrderItemModel>"
        },
        {
            "name": "preferredDeliveryDate",
            "baseName": "preferredDeliveryDate",
            "type": "string"
        },
        {
            "name": "shippingAddressId",
            "baseName": "shippingAddressId",
            "type": "string"
        },
        {
            "name": "shippingOptions",
            "baseName": "shippingOptions",
            "type": "Array<CreateEstimatedOrderRequestShippingOptionsInner>"
        }    ];

    static getAttributeTypeMap() {
        return CreateEstimatedOrderRequest.attributeTypeMap;
    }
}

