/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class DownlinkPingRequest {
    /**
    * ping の試行回数
    */
    'numberOfPingRequests'?: number = 1;
    /**
    * 各 ping 実行のタイムアウト秒数
    */
    'timeoutSeconds'?: number = 1;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "numberOfPingRequests",
            "baseName": "numberOfPingRequests",
            "type": "number"
        },
        {
            "name": "timeoutSeconds",
            "baseName": "timeoutSeconds",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return DownlinkPingRequest.attributeTypeMap;
    }
}

