/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class EmailConfigurationOfBilling {
    /**
    * true の場合、毎月の請求メールに請求書 PDF を添付します（グローバルカバレッジのみ）。
    */
    'attachInvoicePdfEnabled'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "attachInvoicePdfEnabled",
            "baseName": "attachInvoicePdfEnabled",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return EmailConfigurationOfBilling.attributeTypeMap;
    }
}

