/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class EmailsModel {
    'createDateTime'?: number;
    'email'?: string;
    'emailId'?: string;
    'updateDateTime'?: number;
    /**
    * メールアドレス宛てに送信されたトークンを用いて認証済みかどうか
    */
    'verified'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "createDateTime",
            "baseName": "createDateTime",
            "type": "number"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "emailId",
            "baseName": "emailId",
            "type": "string"
        },
        {
            "name": "updateDateTime",
            "baseName": "updateDateTime",
            "type": "number"
        },
        {
            "name": "verified",
            "baseName": "verified",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return EmailsModel.attributeTypeMap;
    }
}

