/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FunnelAWSFirehoseDestination {
    'provider'?: FunnelAWSFirehoseDestination.ProviderEnum;
    'resourceUrl'?: string;
    'service'?: FunnelAWSFirehoseDestination.ServiceEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "FunnelAWSFirehoseDestination.ProviderEnum"
        },
        {
            "name": "resourceUrl",
            "baseName": "resourceUrl",
            "type": "string"
        },
        {
            "name": "service",
            "baseName": "service",
            "type": "FunnelAWSFirehoseDestination.ServiceEnum"
        }    ];

    static getAttributeTypeMap() {
        return FunnelAWSFirehoseDestination.attributeTypeMap;
    }
}

export namespace FunnelAWSFirehoseDestination {
    export enum ProviderEnum {
        Aws = <any> 'aws'
    }
    export enum ServiceEnum {
        Firehose = <any> 'firehose'
    }
}
