/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FunnelOptimCloudiotosDestination {
    'channelId'?: string;
    'dataFormat'?: string;
    'provider'?: FunnelOptimCloudiotosDestination.ProviderEnum;
    'resourceUrl'?: string;
    'service'?: FunnelOptimCloudiotosDestination.ServiceEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "channelId",
            "baseName": "channel_id",
            "type": "string"
        },
        {
            "name": "dataFormat",
            "baseName": "data_format",
            "type": "string"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "FunnelOptimCloudiotosDestination.ProviderEnum"
        },
        {
            "name": "resourceUrl",
            "baseName": "resourceUrl",
            "type": "string"
        },
        {
            "name": "service",
            "baseName": "service",
            "type": "FunnelOptimCloudiotosDestination.ServiceEnum"
        }    ];

    static getAttributeTypeMap() {
        return FunnelOptimCloudiotosDestination.attributeTypeMap;
    }
}

export namespace FunnelOptimCloudiotosDestination {
    export enum ProviderEnum {
        Optim = <any> 'optim'
    }
    export enum ServiceEnum {
        Cloudiotos = <any> 'cloudiotos'
    }
}
