/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FunnelWingarcMotionboardDestination {
    'provider'?: FunnelWingarcMotionboardDestination.ProviderEnum;
    'resourceUrl'?: string;
    'service'?: FunnelWingarcMotionboardDestination.ServiceEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "provider",
            "baseName": "provider",
            "type": "FunnelWingarcMotionboardDestination.ProviderEnum"
        },
        {
            "name": "resourceUrl",
            "baseName": "resourceUrl",
            "type": "string"
        },
        {
            "name": "service",
            "baseName": "service",
            "type": "FunnelWingarcMotionboardDestination.ServiceEnum"
        }    ];

    static getAttributeTypeMap() {
        return FunnelWingarcMotionboardDestination.attributeTypeMap;
    }
}

export namespace FunnelWingarcMotionboardDestination {
    export enum ProviderEnum {
        Wingarc = <any> 'wingarc'
    }
    export enum ServiceEnum {
        Motionboard = <any> 'motionboard'
    }
}
