/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class FunnelEsrijArcgisOnlineDestination {
    'config'?: string;
    'provider'?: FunnelEsrijArcgisOnlineDestination.ProviderEnum;
    'resourceUrl'?: string;
    'service'?: FunnelEsrijArcgisOnlineDestination.ServiceEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "config",
            "baseName": "config",
            "type": "string"
        },
        {
            "name": "provider",
            "baseName": "provider",
            "type": "FunnelEsrijArcgisOnlineDestination.ProviderEnum"
        },
        {
            "name": "resourceUrl",
            "baseName": "resourceUrl",
            "type": "string"
        },
        {
            "name": "service",
            "baseName": "service",
            "type": "FunnelEsrijArcgisOnlineDestination.ServiceEnum"
        }    ];

    static getAttributeTypeMap() {
        return FunnelEsrijArcgisOnlineDestination.attributeTypeMap;
    }
}

export namespace FunnelEsrijArcgisOnlineDestination {
    export enum ProviderEnum {
        Esrij = <any> 'esrij'
    }
    export enum ServiceEnum {
        ArcgisOnline = <any> 'arcgis-online'
    }
}
