/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GadgetLastSeen {
    /**
    * SORACOM LTE-M Button powered by AWS のバッテリーレベル
    */
    'batteryLevel'?: number;
    'clickEventPropagated'?: boolean;
    /**
    * SORACOM LTE-M Button powered by AWS をクリックした日時
    */
    'clickTime'?: Date;
    'clickType'?: GadgetLastSeen.ClickTypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "batteryLevel",
            "baseName": "batteryLevel",
            "type": "number"
        },
        {
            "name": "clickEventPropagated",
            "baseName": "clickEventPropagated",
            "type": "boolean"
        },
        {
            "name": "clickTime",
            "baseName": "clickTime",
            "type": "Date"
        },
        {
            "name": "clickType",
            "baseName": "clickType",
            "type": "GadgetLastSeen.ClickTypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return GadgetLastSeen.attributeTypeMap;
    }
}

export namespace GadgetLastSeen {
    export enum ClickTypeEnum {
        Single = <any> 'SINGLE',
        Double = <any> 'DOUBLE'
    }
}
