/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GetExportedFileResponse {
    /**
    * ファイル出力ステータス
    */
    'status'?: GetExportedFileResponse.StatusEnum;
    /**
    * ファイルダウンロード URL
    */
    'url'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "GetExportedFileResponse.StatusEnum"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GetExportedFileResponse.attributeTypeMap;
    }
}

export namespace GetExportedFileResponse {
    export enum StatusEnum {
        Processing = <any> 'processing',
        Exported = <any> 'exported',
        Failed = <any> 'failed'
    }
}
