/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GetLatestBill {
    /**
    * 金額
    */
    'amount'?: number;
    /**
    * 通貨
    */
    'currency'?: GetLatestBill.CurrencyEnum;
    /**
    * 利用額計算を実施した時間
    */
    'lastEvaluatedTime'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "amount",
            "baseName": "amount",
            "type": "number"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "GetLatestBill.CurrencyEnum"
        },
        {
            "name": "lastEvaluatedTime",
            "baseName": "lastEvaluatedTime",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GetLatestBill.attributeTypeMap;
    }
}

export namespace GetLatestBill {
    export enum CurrencyEnum {
        Jpy = <any> 'JPY',
        Usd = <any> 'USD',
        Eur = <any> 'EUR'
    }
}
