/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { EstimatedOrderItemModel } from './estimatedOrderItemModel';
import { ResourceInitialSetting } from './resourceInitialSetting';
import { ShippingAddressModel } from './shippingAddressModel';

export class GetOrderResponse {
    /**
    * 適用済み配送オプション
    */
    'appliedShippingOptions'?: Array<object>;
    /**
    * 差引請求額
    */
    'balanceDue'?: number;
    'containsTaxIncludedAmounts'?: boolean;
    /**
    * 通貨
    */
    'currency'?: GetOrderResponse.CurrencyEnum;
    /**
    * メールアドレス
    */
    'email'?: string;
    /**
    * 発注チャンネル
    */
    'orderChannel'?: string;
    /**
    * 発注日時 (yyyyMMddHHmmss)
    */
    'orderDateTime'?: string;
    /**
    * 発注 ID
    */
    'orderId'?: string;
    /**
    * 発注商品リスト
    */
    'orderItemList'?: Array<EstimatedOrderItemModel>;
    /**
    * 発注ステータス
    */
    'orderStatus'?: GetOrderResponse.OrderStatusEnum;
    /**
    * 希望納品日
    */
    'preferredDeliveryDate'?: string;
    /**
    * 注文番号
    */
    'purchaseOrderNumber'?: string;
    'resourceInitialSetting'?: ResourceInitialSetting;
    'shippingAddress'?: ShippingAddressModel;
    /**
    * 商品発送先 ID
    */
    'shippingAddressId'?: string;
    /**
    * 配送料
    */
    'shippingCost'?: number;
    /**
    * 宅配便送り状番号 (代表)
    */
    'shippingLabelNumber'?: string;
    /**
    * 宅配便送り状番号
    */
    'shippingLabelNumbers'?: Array<string>;
    /**
    * 税額
    */
    'taxAmount'?: number;
    /**
    * 送料に含まれる税額
    */
    'taxIncludedInShippingCost'?: number;
    /**
    * 配送料の課税有無
    */
    'taxOnShippingCost'?: boolean;
    /**
    * 合計額 (税込)
    */
    'totalAmount'?: number;
    /**
    * 源泉徴収税額
    */
    'withholdingTaxAmount'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "appliedShippingOptions",
            "baseName": "appliedShippingOptions",
            "type": "Array<object>"
        },
        {
            "name": "balanceDue",
            "baseName": "balanceDue",
            "type": "number"
        },
        {
            "name": "containsTaxIncludedAmounts",
            "baseName": "containsTaxIncludedAmounts",
            "type": "boolean"
        },
        {
            "name": "currency",
            "baseName": "currency",
            "type": "GetOrderResponse.CurrencyEnum"
        },
        {
            "name": "email",
            "baseName": "email",
            "type": "string"
        },
        {
            "name": "orderChannel",
            "baseName": "orderChannel",
            "type": "string"
        },
        {
            "name": "orderDateTime",
            "baseName": "orderDateTime",
            "type": "string"
        },
        {
            "name": "orderId",
            "baseName": "orderId",
            "type": "string"
        },
        {
            "name": "orderItemList",
            "baseName": "orderItemList",
            "type": "Array<EstimatedOrderItemModel>"
        },
        {
            "name": "orderStatus",
            "baseName": "orderStatus",
            "type": "GetOrderResponse.OrderStatusEnum"
        },
        {
            "name": "preferredDeliveryDate",
            "baseName": "preferredDeliveryDate",
            "type": "string"
        },
        {
            "name": "purchaseOrderNumber",
            "baseName": "purchaseOrderNumber",
            "type": "string"
        },
        {
            "name": "resourceInitialSetting",
            "baseName": "resourceInitialSetting",
            "type": "ResourceInitialSetting"
        },
        {
            "name": "shippingAddress",
            "baseName": "shippingAddress",
            "type": "ShippingAddressModel"
        },
        {
            "name": "shippingAddressId",
            "baseName": "shippingAddressId",
            "type": "string"
        },
        {
            "name": "shippingCost",
            "baseName": "shippingCost",
            "type": "number"
        },
        {
            "name": "shippingLabelNumber",
            "baseName": "shippingLabelNumber",
            "type": "string"
        },
        {
            "name": "shippingLabelNumbers",
            "baseName": "shippingLabelNumbers",
            "type": "Array<string>"
        },
        {
            "name": "taxAmount",
            "baseName": "taxAmount",
            "type": "number"
        },
        {
            "name": "taxIncludedInShippingCost",
            "baseName": "taxIncludedInShippingCost",
            "type": "number"
        },
        {
            "name": "taxOnShippingCost",
            "baseName": "taxOnShippingCost",
            "type": "boolean"
        },
        {
            "name": "totalAmount",
            "baseName": "totalAmount",
            "type": "number"
        },
        {
            "name": "withholdingTaxAmount",
            "baseName": "withholdingTaxAmount",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return GetOrderResponse.attributeTypeMap;
    }
}

export namespace GetOrderResponse {
    export enum CurrencyEnum {
        Jpy = <any> 'JPY',
        Usd = <any> 'USD',
        Eur = <any> 'EUR'
    }
    export enum OrderStatusEnum {
        Ordering = <any> 'ordering',
        Ordered = <any> 'ordered',
        Kitting = <any> 'kitting',
        Shipped = <any> 'shipped',
        Received = <any> 'received',
        Cancelling = <any> 'cancelling',
        Cancelled = <any> 'cancelled',
        Failed = <any> 'failed'
    }
}
