/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class GetShippingAddressResponse {
    'addressLine1': string;
    'addressLine2'?: string;
    'building'?: string;
    'city': string;
    'companyName'?: string;
    'department'?: string;
    'fullName'?: string;
    'phoneNumber': string;
    /**
    * 配送先 ID
    */
    'shippingAddressId': string;
    /**
    * 配送先エリア
    */
    'shippingArea': string;
    'state': string;
    'zipCode': string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "addressLine1",
            "baseName": "addressLine1",
            "type": "string"
        },
        {
            "name": "addressLine2",
            "baseName": "addressLine2",
            "type": "string"
        },
        {
            "name": "building",
            "baseName": "building",
            "type": "string"
        },
        {
            "name": "city",
            "baseName": "city",
            "type": "string"
        },
        {
            "name": "companyName",
            "baseName": "companyName",
            "type": "string"
        },
        {
            "name": "department",
            "baseName": "department",
            "type": "string"
        },
        {
            "name": "fullName",
            "baseName": "fullName",
            "type": "string"
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string"
        },
        {
            "name": "shippingAddressId",
            "baseName": "shippingAddressId",
            "type": "string"
        },
        {
            "name": "shippingArea",
            "baseName": "shippingArea",
            "type": "string"
        },
        {
            "name": "state",
            "baseName": "state",
            "type": "string"
        },
        {
            "name": "zipCode",
            "baseName": "zipCode",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return GetShippingAddressResponse.attributeTypeMap;
    }
}

