/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class LagoonUserPermissionUpdatingRequest {
    /**
    * A role that represents the permission.
    */
    'role'?: LagoonUserPermissionUpdatingRequest.RoleEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "role",
            "baseName": "role",
            "type": "LagoonUserPermissionUpdatingRequest.RoleEnum"
        }    ];

    static getAttributeTypeMap() {
        return LagoonUserPermissionUpdatingRequest.attributeTypeMap;
    }
}

export namespace LagoonUserPermissionUpdatingRequest {
    export enum RoleEnum {
        Viewer = <any> 'Viewer',
        Editor = <any> 'Editor'
    }
}
