/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { LagoonDashboardPermissionsResponsePermissionsInner } from './lagoonDashboardPermissionsResponsePermissionsInner';

export class LagoonDashboardPermissionsResponse {
    'dashboardId'?: number;
    'dashboardTitle'?: string;
    'permissions'?: Array<LagoonDashboardPermissionsResponsePermissionsInner>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "dashboardId",
            "baseName": "dashboardId",
            "type": "number"
        },
        {
            "name": "dashboardTitle",
            "baseName": "dashboardTitle",
            "type": "string"
        },
        {
            "name": "permissions",
            "baseName": "permissions",
            "type": "Array<LagoonDashboardPermissionsResponsePermissionsInner>"
        }    ];

    static getAttributeTypeMap() {
        return LagoonDashboardPermissionsResponse.attributeTypeMap;
    }
}

