/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { GetShippingAddressResponse } from './getShippingAddressResponse';

export class ListShippingAddressResponse {
    'shippingAddresses'?: Array<GetShippingAddressResponse>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "shippingAddresses",
            "baseName": "shippingAddresses",
            "type": "Array<GetShippingAddressResponse>"
        }    ];

    static getAttributeTypeMap() {
        return ListShippingAddressResponse.attributeTypeMap;
    }
}

