/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CouponResponse } from './couponResponse';

export class ListCouponResponse {
    /**
    * クーポンリスト
    */
    'couponList'?: Array<CouponResponse>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "couponList",
            "baseName": "couponList",
            "type": "Array<CouponResponse>"
        }    ];

    static getAttributeTypeMap() {
        return ListCouponResponse.attributeTypeMap;
    }
}

