/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { LocationRegistrationStatusForNetwork } from './locationRegistrationStatusForNetwork';

export class LocationRegistrationStatus {
    'cs'?: LocationRegistrationStatusForNetwork;
    'eps'?: LocationRegistrationStatusForNetwork;
    'ps'?: LocationRegistrationStatusForNetwork;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cs",
            "baseName": "cs",
            "type": "LocationRegistrationStatusForNetwork"
        },
        {
            "name": "eps",
            "baseName": "eps",
            "type": "LocationRegistrationStatusForNetwork"
        },
        {
            "name": "ps",
            "baseName": "ps",
            "type": "LocationRegistrationStatusForNetwork"
        }    ];

    static getAttributeTypeMap() {
        return LocationRegistrationStatus.attributeTypeMap;
    }
}

