/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class NapterAuditLogDirection {
    'destinationIPAddress'?: string;
    'destinationPort'?: number;
    'sourceIPAddress'?: string;
    'sourcePort'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "destinationIPAddress",
            "baseName": "destinationIPAddress",
            "type": "string"
        },
        {
            "name": "destinationPort",
            "baseName": "destinationPort",
            "type": "number"
        },
        {
            "name": "sourceIPAddress",
            "baseName": "sourceIPAddress",
            "type": "string"
        },
        {
            "name": "sourcePort",
            "baseName": "sourcePort",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return NapterAuditLogDirection.attributeTypeMap;
    }
}

