/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { NapterAuditLogDirection } from './napterAuditLogDirection';

export class NapterAuditLogEntry {
    'connectionId'?: string;
    'createdAt'?: number;
    'direction'?: NapterAuditLogDirection;
    'imsi'?: string;
    'operatorId'?: string;
    'tls'?: boolean;
    'type'?: NapterAuditLogEntry.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "connectionId",
            "baseName": "connectionId",
            "type": "string"
        },
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "number"
        },
        {
            "name": "direction",
            "baseName": "direction",
            "type": "NapterAuditLogDirection"
        },
        {
            "name": "imsi",
            "baseName": "imsi",
            "type": "string"
        },
        {
            "name": "operatorId",
            "baseName": "operatorId",
            "type": "string"
        },
        {
            "name": "tls",
            "baseName": "tls",
            "type": "boolean"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "NapterAuditLogEntry.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return NapterAuditLogEntry.attributeTypeMap;
    }
}

export namespace NapterAuditLogEntry {
    export enum TypeEnum {
        Access = <any> 'ACCESS',
        Denied = <any> 'DENIED',
        Connected = <any> 'CONNECTED',
        Closed = <any> 'CLOSED',
        Refused = <any> 'REFUSED',
        Created = <any> 'CREATED',
        Deleted = <any> 'DELETED',
        Expired = <any> 'EXPIRED'
    }
}
