/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { CoverageType } from './coverageType';
import { SupportTier } from './supportTier';

export class OperatorConfigurationOfSupport {
    'paymentCoverage'?: CoverageType;
    'tier'?: SupportTier;
    'upcomingTier'?: SupportTier;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "paymentCoverage",
            "baseName": "paymentCoverage",
            "type": "CoverageType"
        },
        {
            "name": "tier",
            "baseName": "tier",
            "type": "SupportTier"
        },
        {
            "name": "upcomingTier",
            "baseName": "upcomingTier",
            "type": "SupportTier"
        }    ];

    static getAttributeTypeMap() {
        return OperatorConfigurationOfSupport.attributeTypeMap;
    }
}

export namespace OperatorConfigurationOfSupport {
}
