/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { OperatorConfigurationModelConfiguration } from './operatorConfigurationModelConfiguration';

export class OperatorConfigurationModel {
    'configuration'?: OperatorConfigurationModelConfiguration;
    /**
    * false の場合、コンフィグレーションを setOperatorConfigurationNamespace API で更新できません。
    */
    'isModifiable'?: boolean;
    /**
    * ネームスペースごとに異なる configuration を指定します。詳細は configuration プロパティを参照してください。
    */
    'namespace'?: OperatorConfigurationModel.NamespaceEnum;
    /**
    * コンフィグレーションのバージョン
    */
    'version'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "configuration",
            "baseName": "configuration",
            "type": "OperatorConfigurationModelConfiguration"
        },
        {
            "name": "isModifiable",
            "baseName": "isModifiable",
            "type": "boolean"
        },
        {
            "name": "namespace",
            "baseName": "namespace",
            "type": "OperatorConfigurationModel.NamespaceEnum"
        },
        {
            "name": "version",
            "baseName": "version",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return OperatorConfigurationModel.attributeTypeMap;
    }
}

export namespace OperatorConfigurationModel {
    export enum NamespaceEnum {
        Support = <any> 'Support',
        Email = <any> 'Email'
    }
}
