/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ResourceInstance {
    'description'?: string;
    'id'?: number;
    'mandatory'?: boolean = false;
    'multiple'?: boolean = false;
    'name'?: string;
    'observed'?: boolean = false;
    'operations'?: ResourceInstance.OperationsEnum;
    'rangeEnumeration'?: string;
    'type'?: ResourceInstance.TypeEnum;
    'units'?: string;
    'value'?: object;
    'values'?: object;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number"
        },
        {
            "name": "mandatory",
            "baseName": "mandatory",
            "type": "boolean"
        },
        {
            "name": "multiple",
            "baseName": "multiple",
            "type": "boolean"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "observed",
            "baseName": "observed",
            "type": "boolean"
        },
        {
            "name": "operations",
            "baseName": "operations",
            "type": "ResourceInstance.OperationsEnum"
        },
        {
            "name": "rangeEnumeration",
            "baseName": "rangeEnumeration",
            "type": "string"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ResourceInstance.TypeEnum"
        },
        {
            "name": "units",
            "baseName": "units",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "object"
        },
        {
            "name": "values",
            "baseName": "values",
            "type": "object"
        }    ];

    static getAttributeTypeMap() {
        return ResourceInstance.attributeTypeMap;
    }
}

export namespace ResourceInstance {
    export enum OperationsEnum {
        None = <any> 'NONE',
        R = <any> 'R',
        W = <any> 'W',
        Rw = <any> 'RW',
        E = <any> 'E',
        Re = <any> 'RE',
        We = <any> 'WE',
        Rwe = <any> 'RWE'
    }
    export enum TypeEnum {
        String = <any> 'STRING',
        Integer = <any> 'INTEGER',
        Float = <any> 'FLOAT',
        Boolean = <any> 'BOOLEAN',
        Opaque = <any> 'OPAQUE',
        Time = <any> 'TIME',
        Objlnk = <any> 'OBJLNK'
    }
}
