/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class ResourceSummaryItemValue {
    /**
    * リソースの要約アイテムの集計値の名前  - `resourceSummaryType` が `simsPerStatus` の場合:   - `readySims`: ステータスが「準備完了 (ready)」の IoT SIM の数   - `activeSims`: ステータスが「使用中 (active)」の IoT SIM の数   - `inactiveSims`: ステータスが「休止中 (inactive)」の IoT SIM の数   - `standbySims`: ステータスが「利用開始待ち (standby)」の IoT SIM の数   - `suspendedSims`: ステータスが「利用中断中 (suspended)」の IoT SIM の数 
    */
    'name'?: string;
    /**
    * リソースの要約アイテムの集計値の値
    */
    'value'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "value",
            "baseName": "value",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return ResourceSummaryItemValue.attributeTypeMap;
    }
}

