/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class RuleConfigProperty {
    'inactiveTimeoutDateConst': RuleConfigProperty.InactiveTimeoutDateConstEnum;
    'inactiveTimeoutOffsetMinutes'?: string;
    'limitTotalAmount'?: string;
    'limitTotalTrafficMegaByte'?: string;
    'runOnceAmongTarget'?: RuleConfigProperty.RunOnceAmongTargetEnum;
    /**
    * SimSubscriptionStatusRule の時のみ有効
    */
    'targetOtaStatus'?: RuleConfigProperty.TargetOtaStatusEnum;
    /**
    * SubscriberSpeedClassAttributeRule の時のみ有効
    */
    'targetSpeedClass'?: RuleConfigProperty.TargetSpeedClassEnum;
    /**
    * SubscriberStatusAttributeRule の時のみ有効
    */
    'targetStatus'?: RuleConfigProperty.TargetStatusEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "inactiveTimeoutDateConst",
            "baseName": "inactiveTimeoutDateConst",
            "type": "RuleConfigProperty.InactiveTimeoutDateConstEnum"
        },
        {
            "name": "inactiveTimeoutOffsetMinutes",
            "baseName": "inactiveTimeoutOffsetMinutes",
            "type": "string"
        },
        {
            "name": "limitTotalAmount",
            "baseName": "limitTotalAmount",
            "type": "string"
        },
        {
            "name": "limitTotalTrafficMegaByte",
            "baseName": "limitTotalTrafficMegaByte",
            "type": "string"
        },
        {
            "name": "runOnceAmongTarget",
            "baseName": "runOnceAmongTarget",
            "type": "RuleConfigProperty.RunOnceAmongTargetEnum"
        },
        {
            "name": "targetOtaStatus",
            "baseName": "targetOtaStatus",
            "type": "RuleConfigProperty.TargetOtaStatusEnum"
        },
        {
            "name": "targetSpeedClass",
            "baseName": "targetSpeedClass",
            "type": "RuleConfigProperty.TargetSpeedClassEnum"
        },
        {
            "name": "targetStatus",
            "baseName": "targetStatus",
            "type": "RuleConfigProperty.TargetStatusEnum"
        }    ];

    static getAttributeTypeMap() {
        return RuleConfigProperty.attributeTypeMap;
    }
}

export namespace RuleConfigProperty {
    export enum InactiveTimeoutDateConstEnum {
        Immediately = <any> 'IMMEDIATELY',
        BeginningOfNextMonth = <any> 'BEGINNING_OF_NEXT_MONTH',
        BeginningOfNextDay = <any> 'BEGINNING_OF_NEXT_DAY',
        AfterOneDay = <any> 'AFTER_ONE_DAY',
        Never = <any> 'NEVER'
    }
    export enum RunOnceAmongTargetEnum {
        True = <any> 'true',
        False = <any> 'false'
    }
    export enum TargetOtaStatusEnum {
        Started = <any> 'started',
        Finished = <any> 'finished',
        Failed = <any> 'failed'
    }
    export enum TargetSpeedClassEnum {
        Minimum = <any> 's1.minimum',
        Slow = <any> 's1.slow',
        Standard = <any> 's1.standard',
        Fast = <any> 's1.fast',
        _4xfast = <any> 's1.4xfast'
    }
    export enum TargetStatusEnum {
        Ready = <any> 'ready',
        Active = <any> 'active',
        Inactive = <any> 'inactive',
        Standby = <any> 'standby',
        Suspended = <any> 'suspended',
        Terminated = <any> 'terminated'
    }
}
