/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { RuleConfigProperty } from './ruleConfigProperty';

export class RuleConfig {
    'properties': RuleConfigProperty;
    'type': RuleConfig.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "properties",
            "baseName": "properties",
            "type": "RuleConfigProperty"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "RuleConfig.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return RuleConfig.attributeTypeMap;
    }
}

export namespace RuleConfig {
    export enum TypeEnum {
        SubscriberDailyTrafficRule = <any> 'SubscriberDailyTrafficRule',
        SubscriberMonthlyTrafficRule = <any> 'SubscriberMonthlyTrafficRule',
        SubscriberCumulativeTrafficRule = <any> 'SubscriberCumulativeTrafficRule',
        SubscriberFirstTrafficRule = <any> 'SubscriberFirstTrafficRule',
        SubscriberStatusAttributeRule = <any> 'SubscriberStatusAttributeRule',
        SubscriberSpeedClassAttributeRule = <any> 'SubscriberSpeedClassAttributeRule',
        SubscriberExpiredRule = <any> 'SubscriberExpiredRule',
        SubscriberImeiMismatchedRule = <any> 'SubscriberImeiMismatchedRule',
        SimDailyTotalTrafficRule = <any> 'SimDailyTotalTrafficRule',
        SimMonthlyTotalTrafficRule = <any> 'SimMonthlyTotalTrafficRule',
        SimCumulativeTotalTrafficRule = <any> 'SimCumulativeTotalTrafficRule',
        SimStatusAttributeRule = <any> 'SimStatusAttributeRule',
        SimSpeedClassAttributeRule = <any> 'SimSpeedClassAttributeRule',
        SimExpiredRule = <any> 'SimExpiredRule',
        SimImeiMismatchedRule = <any> 'SimImeiMismatchedRule',
        SimSubscriptionStatusRule = <any> 'SimSubscriptionStatusRule',
        DailyTotalTrafficRule = <any> 'DailyTotalTrafficRule',
        MonthlyTotalTrafficRule = <any> 'MonthlyTotalTrafficRule',
        MonthlyChargeRule = <any> 'MonthlyChargeRule'
    }
}
