/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Cell } from './cell';
import { Placement } from './placement';

export class SessionStatus {
    'cell'?: Cell;
    /**
    * Array of IP address of the DNS servers.
    */
    'dnsServers'?: Array<string>;
    'gatewayPrivateIpAddress'?: string;
    'gatewayPublicIpAddress'?: string;
    /**
    * The IMEI of the device using the SIM.
    */
    'imei'?: string;
    /**
    * IMSI
    */
    'imsi'?: string;
    'lastUpdatedAt'?: number;
    'location'?: object;
    /**
    * セッション状態 - `true`: オンライン - `false`: オフライン 
    */
    'online'?: boolean;
    'placement'?: Placement;
    /**
    * The session ID of the session.
    */
    'sessionId'?: string;
    /**
    * サブスクリプション
    */
    'subscription'?: string;
    /**
    * The IP address of the device.
    */
    'ueIpAddress'?: string;
    /**
    * The Virtual Private Gateway IP address configured.
    */
    'vpgId'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "cell",
            "baseName": "cell",
            "type": "Cell"
        },
        {
            "name": "dnsServers",
            "baseName": "dnsServers",
            "type": "Array<string>"
        },
        {
            "name": "gatewayPrivateIpAddress",
            "baseName": "gatewayPrivateIpAddress",
            "type": "string"
        },
        {
            "name": "gatewayPublicIpAddress",
            "baseName": "gatewayPublicIpAddress",
            "type": "string"
        },
        {
            "name": "imei",
            "baseName": "imei",
            "type": "string"
        },
        {
            "name": "imsi",
            "baseName": "imsi",
            "type": "string"
        },
        {
            "name": "lastUpdatedAt",
            "baseName": "lastUpdatedAt",
            "type": "number"
        },
        {
            "name": "location",
            "baseName": "location",
            "type": "object"
        },
        {
            "name": "online",
            "baseName": "online",
            "type": "boolean"
        },
        {
            "name": "placement",
            "baseName": "placement",
            "type": "Placement"
        },
        {
            "name": "sessionId",
            "baseName": "sessionId",
            "type": "string"
        },
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "string"
        },
        {
            "name": "ueIpAddress",
            "baseName": "ueIpAddress",
            "type": "string"
        },
        {
            "name": "vpgId",
            "baseName": "vpgId",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SessionStatus.attributeTypeMap;
    }
}

