/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SetOperatorConfigurationNamespaceRequestConfiguration } from './setOperatorConfigurationNamespaceRequestConfiguration';

export class SetOperatorConfigurationNamespaceRequest {
    'configuration': SetOperatorConfigurationNamespaceRequestConfiguration;
    /**
    * このプロパティは、更新時のコンフリクトを避けるために利用します。利用する場合、getOperatorConfigurationNamespace API で 取得した version の値をここに指定します。 もし expectedVersion を指定しなかった場合は、更新時にコンフリクトの確認をしません。
    */
    'expectedVersion'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "configuration",
            "baseName": "configuration",
            "type": "SetOperatorConfigurationNamespaceRequestConfiguration"
        },
        {
            "name": "expectedVersion",
            "baseName": "expectedVersion",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SetOperatorConfigurationNamespaceRequest.attributeTypeMap;
    }
}

