/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* 米国およびカナダのオペレーターのみご利用いただけます。
*/
export class ShippingOptionOfExpeditedShipping {
    /**
    * お急ぎ便を使用する場合は true を指定してください。(米国内への発送のみ)
    */
    'useExpeditedShipping'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "useExpeditedShipping",
            "baseName": "useExpeditedShipping",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return ShippingOptionOfExpeditedShipping.attributeTypeMap;
    }
}

