/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { ArcSessionStatus } from './arcSessionStatus';
import { Capabilities } from './capabilities';
import { ImeiLock } from './imeiLock';
import { PreviousSessionStatus } from './previousSessionStatus';
import { SessionStatus } from './sessionStatus';
import { SimProfile } from './simProfile';

export class Sim {
    'activeProfileId'?: string;
    'arcSessionStatus'?: ArcSessionStatus;
    'capabilities'?: Capabilities;
    /**
    * IoT SIM (IoT SIM のプライマリサブスクリプション) が作成された UNIX 時間 (ミリ秒)
    */
    'createdTime'?: number;
    /**
    * 有効期限が切れたときのアクション。詳しくは、[IoT SIM の有効期限とアクションを設定する](/ja-jp/docs/air/set-expiry/) を参照してください。  - `doNothing`: 保留 - `deleteSession`: セッション切断 - `deactivate`: 休止 - `suspend`: 利用中断 - `terminate`: 解約 - `null`: 有効期限が設定されていない 
    */
    'expiryAction'?: Sim.ExpiryActionEnum;
    /**
    * IoT SIM の有効期限 (UNIX 時間 (ミリ秒))
    */
    'expiryTime'?: number;
    /**
    * IoT SIM が所属するグループの ID
    */
    'groupId'?: string;
    'imeiLock'?: ImeiLock;
    /**
    * IoT SIM (IoT SIM のプライマリサブスクリプション) の情報が変更された UNIX 時間 (ミリ秒)
    */
    'lastModifiedTime'?: number;
    /**
    * IoT SIM で Napter が利用された UNIX 時間 (ミリ秒)。 IoT SIM で一度も Napter を利用したことがなければ null です。
    */
    'lastPortMappingCreatedTime'?: number;
    'localInfo'?: { [key: string]: string; };
    /**
    * IoT SIM の形状 (フォームファクタ)  - `mini`: 標準 (2FF) サイズ - `micro`: マイクロ (3FF) サイズ - `nano`: ナノ (4FF) サイズ - `trio`: 3 in 1 (切り取りかた次第で 2FF/3FF/4FF いずれのサイズにもできる) - `embedded`: チップ型 (MFF2 とも呼ばれる組込み型 (eSIM)) - `virtual`: バーチャル SIM/Subscriber 
    */
    'moduleType'?: Sim.ModuleTypeEnum;
    /**
    * IoT SIM を所有しているオペレーターのオペレーター ID
    */
    'operatorId'?: string;
    'otaSerialNumber'?: string;
    'pcapEndTime'?: number;
    'pcapStartTime'?: number;
    'previousSession'?: PreviousSessionStatus;
    'profiles'?: { [key: string]: SimProfile; };
    /**
    * IoT SIM のステータスが「準備完了 (ready)」、「利用開始待ち (standby)」、「利用中断中 (suspended)」のいずれかになった UNIX 時間 (ミリ秒)
    */
    'renewalFeeStatusSetTime'?: number;
    /**
    * IoT SIM のシリアル番号。バーチャル SIM/Subscriber にはシリアル番号はありません。
    */
    'serialNumber'?: string;
    'sessionStatus'?: SessionStatus;
    /**
    * IoT SIM の SIM ID
    */
    'simId'?: string;
    /**
    * IoT SIM の速度クラス
    */
    'speedClass'?: string;
    /**
    * IoT SIM (IoT SIM のプライマリサブスクリプション) のステータス  - `ready`: 準備完了 (ready) - `active`: 使用中 (active) - `inactive`: 休止中 (inactive) - `standby`: 利用開始待ち (standby) - `suspended`: 利用中断中 (suspended) - `terminated`: 解約済み (terminated) 
    */
    'status'?: Sim.StatusEnum;
    /**
    * An object which always contains at least one property \"name\" with a string value. If you give a subscriber/SIM a name, the name will be returned as the value of the \"name\" property. If the subscriber/SIM does not have a name, an empty string \"\" is returned. In addition, if you create any custom tags for the subscriber/SIM, each custom tag will appear as additional properties in the object.
    */
    'tags'?: { [key: string]: string; };
    /**
    * IoT SIM の解約プロテクションの設定  - `true`: 解約プロテクション OFF (解約できる) - `false`: 解約プロテクション ON 
    */
    'terminationEnabled'?: boolean;
    /**
    * IoT SIM のタイプ  - `euicc`: チップ型 (eSIM) - `uicc`: カード型 - `virtual`: バーチャル SIM/Subscriber 
    */
    'type'?: Sim.TypeEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "activeProfileId",
            "baseName": "activeProfileId",
            "type": "string"
        },
        {
            "name": "arcSessionStatus",
            "baseName": "arcSessionStatus",
            "type": "ArcSessionStatus"
        },
        {
            "name": "capabilities",
            "baseName": "capabilities",
            "type": "Capabilities"
        },
        {
            "name": "createdTime",
            "baseName": "createdTime",
            "type": "number"
        },
        {
            "name": "expiryAction",
            "baseName": "expiryAction",
            "type": "Sim.ExpiryActionEnum"
        },
        {
            "name": "expiryTime",
            "baseName": "expiryTime",
            "type": "number"
        },
        {
            "name": "groupId",
            "baseName": "groupId",
            "type": "string"
        },
        {
            "name": "imeiLock",
            "baseName": "imeiLock",
            "type": "ImeiLock"
        },
        {
            "name": "lastModifiedTime",
            "baseName": "lastModifiedTime",
            "type": "number"
        },
        {
            "name": "lastPortMappingCreatedTime",
            "baseName": "lastPortMappingCreatedTime",
            "type": "number"
        },
        {
            "name": "localInfo",
            "baseName": "localInfo",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "moduleType",
            "baseName": "moduleType",
            "type": "Sim.ModuleTypeEnum"
        },
        {
            "name": "operatorId",
            "baseName": "operatorId",
            "type": "string"
        },
        {
            "name": "otaSerialNumber",
            "baseName": "otaSerialNumber",
            "type": "string"
        },
        {
            "name": "pcapEndTime",
            "baseName": "pcapEndTime",
            "type": "number"
        },
        {
            "name": "pcapStartTime",
            "baseName": "pcapStartTime",
            "type": "number"
        },
        {
            "name": "previousSession",
            "baseName": "previousSession",
            "type": "PreviousSessionStatus"
        },
        {
            "name": "profiles",
            "baseName": "profiles",
            "type": "{ [key: string]: SimProfile; }"
        },
        {
            "name": "renewalFeeStatusSetTime",
            "baseName": "renewalFeeStatusSetTime",
            "type": "number"
        },
        {
            "name": "serialNumber",
            "baseName": "serialNumber",
            "type": "string"
        },
        {
            "name": "sessionStatus",
            "baseName": "sessionStatus",
            "type": "SessionStatus"
        },
        {
            "name": "simId",
            "baseName": "simId",
            "type": "string"
        },
        {
            "name": "speedClass",
            "baseName": "speedClass",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "Sim.StatusEnum"
        },
        {
            "name": "tags",
            "baseName": "tags",
            "type": "{ [key: string]: string; }"
        },
        {
            "name": "terminationEnabled",
            "baseName": "terminationEnabled",
            "type": "boolean"
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "Sim.TypeEnum"
        }    ];

    static getAttributeTypeMap() {
        return Sim.attributeTypeMap;
    }
}

export namespace Sim {
    export enum ExpiryActionEnum {
        DoNothing = <any> 'doNothing',
        DeleteSession = <any> 'deleteSession',
        Deactivate = <any> 'deactivate',
        Suspend = <any> 'suspend',
        Terminate = <any> 'terminate',
        NullValue = <any> '(null value)'
    }
    export enum ModuleTypeEnum {
        Mini = <any> 'mini',
        Micro = <any> 'micro',
        Nano = <any> 'nano',
        Trio = <any> 'trio',
        Embedded = <any> 'embedded',
        Virtual = <any> 'virtual'
    }
    export enum StatusEnum {
        Ready = <any> 'ready',
        Active = <any> 'active',
        Inactive = <any> 'inactive',
        Standby = <any> 'standby',
        Suspended = <any> 'suspended',
        Terminated = <any> 'terminated'
    }
    export enum TypeEnum {
        Euicc = <any> 'euicc',
        Uicc = <any> 'uicc',
        Virtual = <any> 'virtual'
    }
}
