/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Capabilities } from './capabilities';

export class SimplifiedSubscriber {
    'bundles'?: Array<string>;
    'capabilities'?: Capabilities;
    /**
    * IMSI
    */
    'imsi'?: string;
    'msisdn'?: string;
    'status'?: string;
    'subscription'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "bundles",
            "baseName": "bundles",
            "type": "Array<string>"
        },
        {
            "name": "capabilities",
            "baseName": "capabilities",
            "type": "Capabilities"
        },
        {
            "name": "imsi",
            "baseName": "imsi",
            "type": "string"
        },
        {
            "name": "msisdn",
            "baseName": "msisdn",
            "type": "string"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "string"
        },
        {
            "name": "subscription",
            "baseName": "subscription",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SimplifiedSubscriber.attributeTypeMap;
    }
}

