/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SmsForwardingRequest {
    /**
    * メッセージ本体のエンコーディングタイプ。デフォルトは `2` (`DCS_UCS2`)。  - `1`: 標準アルファベットをサポートする GSM 7 ビットで送信します。漢字やキリル文字、アラビア文字などは送信できません。最大 160 文字 (最大 140 バイト)。      例: `{\"encodingType\": 1, \"payload\": \"Test message.\"}` - `2`: 漢字やキリル文字、アラビア文字などをサポートする UCS-2 で送信します。最大 70 文字。      例: `{\"encodingType\": 2, \"payload\": \"テストメッセージ\"}` 
    */
    'encodingType'?: number = 2;
    'payload'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "encodingType",
            "baseName": "encodingType",
            "type": "number"
        },
        {
            "name": "payload",
            "baseName": "payload",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SmsForwardingRequest.attributeTypeMap;
    }
}

