/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SoraCamVideoExportInfo {
    /**
    * ソラカメ対応カメラのデバイス ID
    */
    'deviceId'?: string;
    /**
    * URL の有効期限 (UNIX 時間 (ミリ秒))
    */
    'expiryTime'?: number;
    /**
    * エクスポート ID。[`SoraCam:exportSoraCamDeviceRecordedVideo API`](/ja-jp/tools/api/reference/#/SoraCam/exportSoraCamDeviceRecordedVideo) で取得したエクスポート ID を、[`SoraCam:getSoraCamDeviceExportedVideo API`](/ja-jp/tools/api/reference/#/SoraCam/getSoraCamDeviceExportedVideo) で指定すると、mp4 ファイルを zip 形式で圧縮したファイルをダウンロードするための URL を取得できます。 
    */
    'exportId'?: string;
    /**
    * [`SoraCam:exportSoraCamDeviceRecordedVideo API`](/ja-jp/tools/api/reference/#/SoraCam/exportSoraCamDeviceRecordedVideo) を呼び出したオペレーターの ID 
    */
    'operatorId'?: string;
    /**
    * [`SoraCam:exportSoraCamDeviceRecordedVideo API`](/ja-jp/tools/api/reference/#/SoraCam/exportSoraCamDeviceRecordedVideo) によるエクスポートのリクエストを SORACOM プラットフォームが受け付けた日時 (UNIX 時間 (ミリ秒)) 
    */
    'requestedTime'?: number;
    /**
    * エクスポート処理の現在の状況。  - `initializing`: 初期状態 - `processing`: 処理中 - `completed`: エクスポート完了 - `retrying`: エクスポート再実行中 - `failed`: エクスポート失敗 - `limitExceeded`: 動画のエクスポート可能時間の上限を超えたためエクスポート不可 - `expired`: URL の有効期限切れ 
    */
    'status'?: SoraCamVideoExportInfo.StatusEnum;
    /**
    * mp4 ファイルを zip 形式で圧縮したファイルをダウンロードするための URL。`status` が `completed` の場合のみ含まれます。  - ダウンロードした zip 形式のファイルを展開すると、mp4 ファイルを取得できます。 
    */
    'url'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "deviceId",
            "baseName": "deviceId",
            "type": "string"
        },
        {
            "name": "expiryTime",
            "baseName": "expiryTime",
            "type": "number"
        },
        {
            "name": "exportId",
            "baseName": "exportId",
            "type": "string"
        },
        {
            "name": "operatorId",
            "baseName": "operatorId",
            "type": "string"
        },
        {
            "name": "requestedTime",
            "baseName": "requestedTime",
            "type": "number"
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "SoraCamVideoExportInfo.StatusEnum"
        },
        {
            "name": "url",
            "baseName": "url",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SoraCamVideoExportInfo.attributeTypeMap;
    }
}

export namespace SoraCamVideoExportInfo {
    export enum StatusEnum {
        Initializing = <any> 'initializing',
        Processing = <any> 'processing',
        Completed = <any> 'completed',
        Retrying = <any> 'retrying',
        Failed = <any> 'failed',
        LimitExceeded = <any> 'limitExceeded',
        Expired = <any> 'expired'
    }
}
