/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SoraCamVideoExportSpecification {
    /**
    * エクスポート対象の開始時刻 (UNIX 時間 (ミリ秒))
    */
    'from': number;
    /**
    * エクスポート対象の終了時刻 (UNIX 時間 (ミリ秒))  - 一回の API 呼び出しでエクスポートできる時間は最大 300 秒 (5 分) です。`from` と `to` の差が、300 秒を超えないようにしてください。 
    */
    'to': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "from",
            "baseName": "from",
            "type": "number"
        },
        {
            "name": "to",
            "baseName": "to",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SoraCamVideoExportSpecification.attributeTypeMap;
    }
}

