/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SoraCamEventEventInfoAtomEventV1 } from './soraCamEventEventInfoAtomEventV1';

export class SoraCamEventEventInfo {
    'atomEventV1'?: SoraCamEventEventInfoAtomEventV1;
    /**
    * イベント詳細のタイプ。デバイスのタイプによって変更される場合があります。
    */
    'infoType'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "atomEventV1",
            "baseName": "atomEventV1",
            "type": "SoraCamEventEventInfoAtomEventV1"
        },
        {
            "name": "infoType",
            "baseName": "infoType",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SoraCamEventEventInfo.attributeTypeMap;
    }
}

