/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

/**
* ソラカメ対応カメラのコンフィグレーション
*/
export class SoraCamDeviceConfiguration {
    /**
    * 音声アラームが有効化されているかどうか
    */
    'audioAlarmEnabled'?: boolean;
    /**
    * モーション検知が有効化されているかどうか
    */
    'motionDetectionEnabled'?: boolean;
    /**
    * 煙検知が有効化されているかどうか
    */
    'smokeAlarmEnabled'?: boolean;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "audioAlarmEnabled",
            "baseName": "audioAlarmEnabled",
            "type": "boolean"
        },
        {
            "name": "motionDetectionEnabled",
            "baseName": "motionDetectionEnabled",
            "type": "boolean"
        },
        {
            "name": "smokeAlarmEnabled",
            "baseName": "smokeAlarmEnabled",
            "type": "boolean"
        }    ];

    static getAttributeTypeMap() {
        return SoraCamDeviceConfiguration.attributeTypeMap;
    }
}

