/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SoraCamLicensePackResponse {
    /**
    * ライセンスパックの ID
    */
    'id'?: string;
    /**
    * ライセンスパックの名前
    */
    'name'?: string;
    /**
    * 現在のライセンス数
    */
    'quantity'?: number;
    /**
    * ライセンスパックの販売元
    */
    'salesChannel'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string"
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string"
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number"
        },
        {
            "name": "salesChannel",
            "baseName": "salesChannel",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SoraCamLicensePackResponse.attributeTypeMap;
    }
}

