/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class SoraCamImageExportUsage {
    /**
    * 課金対象の動画のエクスポート可能時間について、すべて静止画でエクスポートしたとみなした場合の静止画の枚数。つまり、0 のときは課金が発生していません。なお、課金額の計算には、`billedSeconds` のみが使用されます。
    */
    'billedFrames'?: number;
    /**
    * 動画のエクスポート可能時間の上限まで、すべて静止画でエクスポートしたとみなした場合の静止画の枚数。動画のエクスポート可能時間の上限が、静止画の枚数で出力されます。
    */
    'limitFrames'?: number;
    /**
    * 動画のエクスポート可能時間の上限まで、すべて静止画でエクスポートすると仮定した場合の、エクスポート可能な静止画の枚数。`limitFrames` から `usedFrames` を引いた値です。
    */
    'remainingFrames'?: number;
    /**
    * 当月に消費した動画のエクスポート可能時間を、すべて静止画でエクスポートしたとみなした場合の、エクスポートした静止画の枚数。
    */
    'usedFrames'?: number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "billedFrames",
            "baseName": "billedFrames",
            "type": "number"
        },
        {
            "name": "limitFrames",
            "baseName": "limitFrames",
            "type": "number"
        },
        {
            "name": "remainingFrames",
            "baseName": "remainingFrames",
            "type": "number"
        },
        {
            "name": "usedFrames",
            "baseName": "usedFrames",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return SoraCamImageExportUsage.attributeTypeMap;
    }
}

