/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SoraCamImageExportUsage } from './soraCamImageExportUsage';
import { SoraCamVideoExportUsage } from './soraCamVideoExportUsage';

export class SoraCamExportUsage {
    /**
    * ソラカメ対応カメラのデバイス ID
    */
    'deviceId'?: string;
    'image'?: SoraCamImageExportUsage;
    /**
    * 動画のエクスポート可能時間の対象年月 (フォーマット: \'YYYYMM\')。`202301` の場合は、2023 年 1 月の動画のエクスポート可能時間が出力されていることを表します。
    */
    'meteredYearMonth'?: string;
    'video'?: SoraCamVideoExportUsage;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "deviceId",
            "baseName": "deviceId",
            "type": "string"
        },
        {
            "name": "image",
            "baseName": "image",
            "type": "SoraCamImageExportUsage"
        },
        {
            "name": "meteredYearMonth",
            "baseName": "meteredYearMonth",
            "type": "string"
        },
        {
            "name": "video",
            "baseName": "video",
            "type": "SoraCamVideoExportUsage"
        }    ];

    static getAttributeTypeMap() {
        return SoraCamExportUsage.attributeTypeMap;
    }
}

