/**
 * SORACOM API
 * SORACOM API v1
 *
 * The version of the OpenAPI document: 20230427-035008
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { SubscriptionContainerStatusCountryMappingValueMappingRecord } from './subscriptionContainerStatusCountryMappingValueMappingRecord';

export class SubscriptionContainerStatusCountryMappingValue {
    'mappingRecord'?: SubscriptionContainerStatusCountryMappingValueMappingRecord;
    'plmnCode'?: string;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "mappingRecord",
            "baseName": "mappingRecord",
            "type": "SubscriptionContainerStatusCountryMappingValueMappingRecord"
        },
        {
            "name": "plmnCode",
            "baseName": "plmnCode",
            "type": "string"
        }    ];

    static getAttributeTypeMap() {
        return SubscriptionContainerStatusCountryMappingValue.attributeTypeMap;
    }
}

