name: CI/lint and build

on:
  push:
    branches: [ add-lint ]
  workflow_dispatch:

jobs:
  lint-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install npm packages
        run: npm install
      - name: lint
        run: npm run lint
      - name: build
        run: npm run build
      - name: ncc
        run: npm run ncc
